### ISSUE TITLE
smoothn function not found

### ISSUE THREAD

**Issue by prlabu** [mullerlab/generalized-phase#2]
I'm trying to reproduce the demo code and got the following error without making any changes to the code. I searched in both the **wave** toolbox and within the generalized-phase. Also checked to make sure it's not a MATLAB native function. Any thoughts? 

```
Undefined function or variable 'smoothn'.

Error in find_source_points (line 22)
d = smoothn( d, 'robust' );

Error in spontaneous_wave_demo (line 58)
    source = find_source_points( evaluation_points, X, Y, dx, dy );
```

**Comment by neuroptics** [comment]
Hi Latane,

You can fine the 'smoothn' function here:
https://www.mathworks.com/matlabcentral/fileexchange/25634-smoothn

David

**Comment by prlabu** [comment]
Great, thanks!
